### ISSUE TITLE
remote version of `install-packages`

### ISSUE THREAD

**Issue by wibeasley** [OuhscBbmc/RedcapExamplesAndPatterns#12]
@caston60 brought up a use case where a GitHub gist is better suited for installing a bunch of packages than installing this repo (and keeping it up-to-date) just for the single function.

repo's function: https://github.com/OuhscBbmc/RedcapExamplesAndPatterns/blob/master/utility/install-packages.R

gist's function (so far): https://gist.github.com/wibeasley/2c5e7459b88ec28b9e8fa0c695b15ee3

**Comment by mand9472** [comment]
@wibeasley , does the function here has to be  ```OuhscMunge:::package_janitor_remote(path_csv)``` ?
https://github.com/OuhscBbmc/RedcapExamplesAndPatterns/blob/5b2b4737f79d05ac5c4124c08a13b037320d9d55/utility/install-packages.R#L22

It looks like you modified it in this commit.

https://github.com/OuhscBbmc/OuhscMunge/commit/315b34c32f0762e67d827d5ed8039bb513854a5b
