### ISSUE TITLE
GitHub Issue Assignment/Exercise

### ISSUE THREAD

**Issue by wibeasley** [OuhscBbmc/RedcapExamplesAndPatterns#3]
GitHub 'Milestones' and 'Issues' are a critical piece of our research projects.  They've help coordinate many developers and statisticians working on a single project and code base.  Communication can be enhanced learning how to include more than just plain text in the issues.  These touches make it easier for the reader to make connections between the post and the code.

Item 1: Create a link that will always refer to the _most current_ version of a file, even if the file is updated after the post.

Item 2: Create a link that will refer to a snapshot of a file.  So when the file is updated, the pointer does NOT refer to the newer version.

Item 3: Refer to a _specific line of code_ in a snapshot of a file.

Item 4: Refer to a _block of code_ in a snapshot of a file.

Item 5: Refer to another GitHub issue.

Item 6: Refer to another GitHub user.

Item 7: Hide the full url of the item 1, and display just "item 1"

Item 8: Format in-line code (eg, a variable name)

Item 9: Format a block of code.

Item 10: Refer to GitHub "diff".  This allows the reader to look at the red & green lines on one screen, instead of flipping back and forth between two versions/pages.

Item 11: Create 'tasks' within an issue.  GitHub released an extension to their version of markdown. It allows you to create a list of 'tasks' within an issue. https://github.com/blog/1375-task-lists-in-gfm-issues-pulls-comments  See an example in the [comment below](https://github.com/OuhscBbmc/RedcapApiExample/issues/3#issuecomment-21321986):

**Comment by mand9472** [comment]
* item 1
https://github.com/OuhscBbmc/RedcapExamplesAndPatterns/blob/master/documentation_patterns/ellis.md

* item 2
https://github.com/OuhscBbmc/RedcapExamplesAndPatterns/blob/67238602b847badc9a04978513b06dd4eec228c0/documentation_patterns/ellis.md

* item 3
https://github.com/OuhscBbmc/RedcapExamplesAndPatterns/blob/67238602b847badc9a04978513b06dd4eec228c0/manipulation/groom_cars.R#L16

* item 4
https://github.com/OuhscBbmc/RedcapExamplesAndPatterns/blob/67238602b847badc9a04978513b06dd4eec228c0/manipulation/groom_cars.R#L18-L20

* item 5
#7 

* item 6
@wibeasley 


* item 7
[item 1](https://github.com/OuhscBbmc/RedcapExamplesAndPatterns/blob/master/documentation_patterns/ellis.md
)

* item 8
`suppressStartupMessages <- TRUE`

* item 9
```
suppressStartupMessages <- TRUE
require(knitr, quietly=suppressStartupMessages)
require(ggplot2, quietly=suppressStartupMessages)
require(Rcpp, quietly=suppressStartupMessages)
require(RCurl, quietly=suppressStartupMessages)
```

* item 10
https://github.com/OuhscBbmc/PrairieOutpost/commit/d6df81ff0e4f038d7a6223cc5b63b1edb1c8fd91#diff-ef26edf9e7ed10e35f64884bae6956c7

* item 11
- [ ] task 1
- [ ] task 2
- [x] task 3
