### ISSUE TITLE
Re: Updating R & Ecosystem

### ISSUE THREAD

**Issue by caston60** [OuhscBbmc/RedcapExamplesAndPatterns#9]
Open R Studio using RedcapExamplesAndPatterns.Rproj

Run install-packages.R   (chose "Save as personal file" [Okay] ... then took awhile but no errors spotted)

Run 
if( !require("remotes") ) install.packages("remotes")
update(remotes::dev_package_deps())

Console:
> if( !require("remotes") ) install.packages("remotes")
Loading required packages: remotes
> update(remotes::dev_package_deps())
Error in read.dcf(path) : cannot open the connection
In addition: Warning message:
In read.dcf(path) 
  cannot open compressed file 'c:\Users\caston\Documents\GitHub\RedccapExamplesAndPatterns-master/DESCRIPTION', probable reason 'No such file or directory'
>

**Comment by wibeasley** [comment]
@caston60, this code is to update the miechv3 project.  Make sure that your run that in the miechv3 RStudio project.
